spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/clockedin
spring.datasource.username=clockedin
spring.datasource.password=clockedin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=ildg5PmJtWdfKYFJYtcttG8evOCyr7q7YvjvNSBHlNQ=
app.jwt.expiration-ms=86400000

server.port=8080
